' Snake art generated by ASCIIArt from the snake icon (snakeIcon.png)
' https://github.com/morphx666/ASCIIArt
Public Class AsciiSnake
    Public Shared Sub Render()
        Dim x As Integer = Console.CursorLeft
        Dim y As Integer = Console.CursorTop
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("       ")
        Console.ForegroundColor = ConsoleColor.DarkRed
        Console.Write("░")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("░")
        Console.Write("░")
        Console.Write("                                        ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("      ")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("▒")
        Console.Write("▒")
        Console.Write("▓")
        Console.ForegroundColor = ConsoleColor.DarkYellow
        Console.Write("▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("░")
        Console.Write("                                     ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.DarkRed
        Console.Write("    ")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("░")
        Console.Write("▒")
        Console.Write("▓")
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("▒▒▒▒▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("░")
        Console.Write("                                   ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("   ")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("░")
        Console.Write("███")
        Console.Write("▓")
        Console.Write("▒▒▒▒▒")
        Console.Write("███")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("▒")
        Console.Write("                                  ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("   ")
        Console.Write("▓")
        Console.Write("█")
        Console.Write("▓▓")
        Console.Write("█")
        Console.Write("▒▒▒▒")
        Console.Write("▓")
        Console.Write("█")
        Console.Write("▓")
        Console.Write("█")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("▓")
        Console.Write("                                  ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("   ")
        Console.Write("▒")
        Console.Write("▓")
        Console.Write("██")
        Console.Write("▒▒▒▒▒▒")
        Console.Write("██")
        Console.Write("▓")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("▒")
        Console.Write("                                  ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("  ")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("▒▒▒▒▒▒▒▒▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.DarkYellow
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("░")
        Console.Write("                                 ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.Write(" ")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("░")
        Console.Write("▒")
        Console.Write("▓")
        Console.ForegroundColor = ConsoleColor.DarkRed
        Console.Write("▒▒▒▒▒▒▒▒▒▒▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("░")
        Console.Write("                                ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write(" ")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("░")
        Console.Write("▓▓")
        Console.ForegroundColor = ConsoleColor.DarkYellow
        Console.Write("▒▒▒▒▒▒▒▒▒▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("▒▒")
        Console.Write("                                ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.DarkYellow
        Console.Write(" ")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("░")
        Console.ForegroundColor = ConsoleColor.DarkYellow
        Console.Write("▒▒▒▒▒▒▒▒▒▒▒▒▒▒")
        Console.Write("▒▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("░")
        Console.Write("                                ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("  ")
        Console.ForegroundColor = ConsoleColor.DarkRed
        Console.Write("▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("░")
        Console.Write("                                ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.DarkRed
        Console.Write("  ")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("░")
        Console.ForegroundColor = ConsoleColor.Yellow
        Console.Write("▒▒▒▒▒▒▒▒▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("▒")
        Console.Write("░")
        Console.Write("                                ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("    ")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("▒▒▒▒▒▒▒▒▒▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.DarkYellow
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.DarkYellow
        Console.Write("▒")
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("░")
        Console.Write("░")
        Console.Write("                          ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.Write("      ")
        Console.ForegroundColor = ConsoleColor.DarkYellow
        Console.Write("░")
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("░")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("▒▒")
        Console.Write("▒▒▒")
        Console.Write("▓▓")
        Console.ForegroundColor = ConsoleColor.DarkYellow
        Console.Write("▒▒▒▒▒▒▒▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("░")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("▒")
        Console.Write("                      ")
        Console.SetCursorPosition(x, Console.CursorTop + 1)
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("           ")
        Console.Write("▒")
        Console.Write("▓▓▓▓")
        Console.ForegroundColor = ConsoleColor.Gray
        Console.Write("▒▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.White
        Console.Write("▒")
        Console.ForegroundColor = ConsoleColor.DarkRed
        Console.Write("▒▒▒▒▒▒")
        Console.ForegroundColor = ConsoleColor.Black
        Console.Write("░")
    End Sub
End Class
